### ISSUE TITLE
Error when running `make technichub`

### ISSUE THREAD

**Issue by Mantarri** [pybricks/pybricks-micropython#237] opened 2024-02-25 08:26 UTC
Environment:

- **OS:** openSUSE Tumbleweed (last updated Feb. 24, 2024 as its a rolling-release) running in VirtualBox 7.0.14
- **Allocated RAM:** 6GB
- **Allocated CPU Cores:** 2
- **Host CPU:** Ryzen 5 5600X
- **Host RAM:** 32GB
- **Python:** 3.10.13
- **Poetry:** 1.7.1
- **arm-gcc:** 10-2020-q4-major
- **Make:** 4.4.1
- **CMake:** 3.28.1

I followed the setup guide in `contributing.md` (though I did get this potential error: `The current project could not be installed: No file/folder found for package pybricks-micropython`)

Anyway. When I run `make technichub` from my `pybricks-micropython` folder, I get the following:
```
make[1]: Entering directory '/home/mantadev/Documents/git/lego/pybricks/pybricks-micropython/micropython/mpy-cross'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
CC ../py/stackctrl.c
../py/stackctrl.c: In function ‘mp_stack_ctrl_init’:
../py/stackctrl.c:32:32: error: storing the address of local variable ‘stack_dummy’ in ‘mp_state_ctx.thread.stack_top’ [-Werror=dangling-pointer=]
   32 |     MP_STATE_THREAD(stack_top) = (char *)&stack_dummy;
../py/stackctrl.c:31:18: note: ‘stack_dummy’ declared here
   31 |     volatile int stack_dummy;
      |                  ^~~~~~~~~~~
In file included from ../py/runtime.h:29,
                 from ../py/stackctrl.c:27:
../py/mpstate.h:296:23: note: ‘mp_state_ctx’ declared here
  296 | extern mp_state_ctx_t mp_state_ctx;
      |                       ^~~~~~~~~~~~
cc1: all warnings being treated as errors
See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
make[1]: *** [../py/mkrules.mk:83: build/py/stackctrl.o] Error 1
make[1]: Leaving directory '/home/mantadev/Documents/git/lego/pybricks/pybricks-micropython/micropython/mpy-cross'
make: *** [Makefile:123: mpy-cross] Error 2
```

**Comment by laurensvalk** [comment] 2024-02-26 09:32
Duplicate of https://github.com/pybricks/support/issues/1481, so let's continue there.

**Closed by laurensvalk** 2024-02-26 09:32 UTC
